# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

complexity:
  TooManyFunctions:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: false

formatting:
  Indentation:
    active: true
  NoBlankLineBeforeRbrace:
    active: false
  NoWildcardImports:
    # Some files import enum constants using wildcard imports :)
    active: false

style:
  WildcardImport:
    # Same as formatting.NoWildcardImports
    active: false
