# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

complexity:
  TooManyFunctions:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: false

formatting:
  Indentation:
    active: true
  NoBlankLineBeforeRbrace:
    active: false
